version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/apache/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/var/www/html:cached
      - var:/var/www/html/var
      - logs:/var/www/html/var/log
      - vendor:/var/www/html/vendor
      - ./public/build:/var/www/html/public/build  # Mount the Webpack build output

    extra_hosts:
      - "localhost:127.0.0.1"
    ports:
      - 8000:80
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oximax
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ABSOLUTE_URI=http://localhost:8080
      - PMA_FORCE_HTTP=true
    depends_on:
      - db

volumes:
  db-data:
  var:  # Define the "var" volume
  vendor:  # Define the "vendor" volume
  logs:  # Define the "logs" volume

